### ISSUE TITLE
Why not reconnect to Nagios Server(NDOUtils/MySQL)? .

### ISSUE THREAD

**Issue by o-wakabayashi** [project-hatohol/hatohol#499]
If disconnect at the failure of Nagios Server(NDOUtils/MySQL), will not be re-connected after recovery. 
However, should be re-connected to the Nagios Server automatically after recovery (zabbix similarly).
Otherwise, disconnect event is not resolved.

**Comment by Mnakagawa** [comment]
I confirmed to reconnect to Nagios Server.
I will write procedure at that time in the following.

1.Register Nagios&NDOUtils on Hatohol and confirm a status to be "OK".
2.Shutdown a machine that has Nagios Server&NDOUtils.
3.Confirm a status becoming "Error".
4.Power on that machine.
5.Confirm a status becoming "OK".

So, I think this issue was resolved.
I advance to close this issue.

**Comment by ashie** [comment]
I confirmed to reconnect to Nagios Server.

It seems that @o-wakabayashi fixes this issue at 5c9efd3.
